### ISSUE TITLE
too much

### ISSUE THREAD

**Issue by Sergey-Gusarov** [sergey-kotov-architect/allocation#1]
if you use the constructor to inject @Autowired there is no need
you can also use Lombok, but this is less obvious

@RestController
@RequestMapping("/api/v1/actor")
@RequiredArgsConstructor
public class ActorController {
    private final ActorService actorService;
****other code***

please correct my english ;)

https://github.com/sergey-kotov-architect/allocation/blob/55e2bac3b27677c4e679415526163616d6c6c468/src/main/java/com/sergeykotov/allocation/controller/ActorController.java#L15

**Comment by sergey-kotov-architect** [comment]
Correct, the annotation is not required for the constructor level injection. However, it seems a good practice to explicitly underline that the dependency injection is handled by the framework, at least, I noticed it in high quality tutorials and heard such advice, and I agree that it makes code slightly more readable, it is not always easy for yourself and everyone to remember every default behaviour of every aspect of every version of every framework.
